[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "latex_to_markdown"
version = "0.0.1"
description = "convert latex to markdown"
requires-python = ">=3.7"


